<?php


namespace app\controllers;



use app\models\Verify;
use dektrium\user\models\Profile;
use dektrium\user\models\User;
use yii\web\Controller;
use app\models\Job;
use app\models\Bids;
use app\models\Message;
use Yii;
use app\models\Category;
use app\models\cities;

class AccountController extends Controller
{

    public function init()
    {
       if(Yii::$app->user->isGuest)
       {
           return $this->goHome();
       }; // TODO: Change the autogenerated stub
    }

    public function actionIndex($name)
    {

        //Find the user by Username
        #usernames are unique so don't worry.
        $data['user'] =  User::find()->where(['username'=>$name])->one();
        //Get the userId
        $data['userId'] = $data['user']->id;
        if(Yii::$app->user->id === $data['userId'] && !Yii::$app->user->isGuest){
            //It's the users account
            $data['userOwnAccount'] = true;
            //The account has it's own layouts.
            $this->layout = 'account/main';
            //Find the Profile of the user by userId
            $data['profile'] = Profile::findOne($userId);
            $data['ward'] = 'name';
            //Verify Form
            $data['verify'] = new Verify();

//            echo 'you can edit this is your profile';
        } else {
            echo 'you are looking at another profile';
        }

        return $this->render('index',compact('data'));
    }

}