<?php


namespace app\controllers;



use app\models\Latestwork;
use app\models\Review;
use app\models\Verify;
use dektrium\user\models\Profile;
use dektrium\user\models\User;
use yii\web\Controller;
use app\models\Job;
use app\models\Bids;
use app\models\Message;
use Yii;
use app\models\Category;
use app\models\cities;

class AccountController extends Controller
{

    public function init()
    {
       if(Yii::$app->user->isGuest)
       {
           return $this->goHome();
       }; // TODO: Change the autogenerated stub
    }

    public function actionIndex($name)
    {
        //Find the user by Username
        #usernames are unique so don't worry.
        $data['user'] =  User::find()->where(['username'=>$name])->one();
        //Get the userId
        $data['userId'] = $data['user']->id;
        if(Yii::$app->user->id === $data['userId'] && !Yii::$app->user->isGuest){
            //It's the users account
            $data['userOwnAccount'] = true;
            //The account has it's own layouts.
            $this->layout = 'account/main';
            //Find the Profile of the user by userId
            $data['profile'] =Yii::$app->user->identity->profile;
            //Number of jobs user wrote
            $data['jobsOffered'] = Job::getJobCountForUser($data['userId']);
            //Number of bids user made
            $data['bidsMade'] = Bids::getBidsCountForUser($data['userId']);
            //Number of jobs that is done
            $data['jobsDone'] = Bids::getBidsDoneCountForUser($data['userId']);
            //Number of reviews written about this user
            $data['reviewsAboutUser'] = Review::getReviewsCountAboutUser($data['userId']);
            //Names of favorite Categories
            $data['favoriteCategories'] = Category::getCategoryNames(explode(',',$data['profile']->fav_categories ));
            //Latest work - path/url
            $data['latestWork'] = Latestwork::getLatestWorkForProfileInput($data['userId']);


            //Messages
            $data['messages'] = Message::getMessages($data['userId']);

            //Jobs for current user
            $data['jobs'] = Job::getJobs($data['userId']);


            //Bids for current user
            $data['bids'] = Bids::getBidsForUser($data['userId']);


            $data['userRequestedVerify'] = Verify::getUserRequest($data['userId']);

            $data['ward'] = 'name';
            //Verify Form
            $data['verify'] = new Verify();
            return $this->render('index',compact('data'));
//            echo 'you can edit this is your profile';
        } else {
            echo 'you are looking at another profile';
        }

    }

}