<?php


namespace app\controllers;


use yii\web\Controller;
use dektrium\user\models\User;
use app\models\Job;
use app\models\Bids;
use dektrium\user\models\Profile;
use Yii;

class AccountController extends Controller
{
    public function init()
    {
       if(Yii::$app->user->isGuest)
       {
           return $this->goHome();
       }; // TODO: Change the autogenerated stub
    }

    public function actionIndex($name)
    {

        //The account has it's own layouts.
        $this->layout = 'account/main';
        //Find the user by Username
        #usernames are unique so don't worry.
        $user =  User::find()->where(['username'=>$name])->one();
        //Get the userId
        $userId = $user->id;
        //Find the Profile of the user by userId
        $profile = Profile::findOne($userId);
        if(Yii::$app->user->id === $userId && !Yii::$app->user->isGuest){


//            echo 'you can edit this is your profile';
        } else {
//            echo 'you are looking at another profile';
        }

        return $this->render('index');
    }

}