<?php


namespace app\models;


use yii\db\ActiveRecord;

class Bids extends ActiveRecord
{


    /**
     * @property integer $status
     * @property string  $title
     * @property string  $description
     * @property integer $paid
     * @property integer $job_id
     * @property integer $user_id
     * @property datetime $create_date
     */
    public static function tableName()
    {
        return 'bids'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
           [['title','description'] , 'string'],
            [['paid','job_id','user_id'],'integer'],
            [['paid','title','description'], 'required']
        ]; // TODO: Change the autogenerated stub
    }
    public function getJobonbid()
    {
        return $this->hasMany(Job::className(),['id'=>'job_id']);
    }
}