<?php


namespace app\models;


use yii\db\ActiveRecord;

class Help extends ActiveRecord
{


    /**
     * This is the model class for table "contact".
     *
     * @property int $id
     * @property string|null $question
     * @property string|null $how
     */


    public static function tableName()
    {
        return 'help';
    }

    public function rules() {

        return [
          [['question','how'], 'required'],
          [['question','how'], 'string' , 'max' => 250],
        ];
    }

    public function formName()
    {
        return 'help-form'; // TODO: Change the autogenerated stub
    }
}