<?php


namespace app\models;


use DateTime;
use yii\base\Model;
use yii\db\ActiveRecord;

class Job extends ActiveRecord
{
    /**
     * This is the model class for table "joboffer".
     *@property TYPE_DATETIME $date_expire
     * @property int $id
     * @property string|null $title
     * @property string|null $description
     * @property string|null $howlong;
     * @property string|null $place;
     * @property int|null $pay;
     * @property string|null $category;
     * * @property string|null $link;
     */

    public static function tableName()
    {
        return 'joboffer';
    }

    public function rules() {
        return [
            [['title','description','howlong', 'place', 'pay','category','expire_date'] , 'required'],
            [['title','description','howlong','place','category','link'], 'string' , 'max' => 250],
     //       [['expire_date'], 'time'],
     //       [['expire_date'], 'default', 'value'=>date('yyyy-mm-dd hh:i:ss')],
            ['pay', 'number'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'description' => 'description',
            'howlong' => 'For how long is the job?',
            'place' => 'in which city?',
            'pay' => 'how much are you going to pay?',
            'category' => 'in which category?',
            'expire_date' => 'For how long this job is valid?'
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Profile::class, ['user_id' => 'user_id'])->alias('author');
    }

    public function getJobsForUser()
    {
        return $this->hasMany(User::className(),['user_id'=>'id'])->alias('user');
    }

    public function getBidonjob()
    {
        return $this->hasMany(Bids::className(),['job_id'=>'id']);
    }
}