<?php


namespace app\models;


use yii\db\ActiveRecord;
use dektrium\user\traits\ModuleTrait;

class Latestwork extends ActiveRecord
{
    use ModuleTrait;
    /** @var \dektrium\user\Module */
    protected $module;
    public function rules()
    {
        return  [
                [['photos'],'file','skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg' , 'maxFiles' => 4],
                ];
    }

    public static function tableName()
    {
        return 'latest_work'; // TODO: Change the autogenerated stub
    }

    /**
     * @Param $user_id integer
     *  returns the latest work for current user to show it in the profile field
     * @return array|ActiveRecord
     */

    public function getLatestWorkForProfileInput(int $user_id)
    {
       $latestwork = Latestwork::find()
            ->where(['user_id' => $user_id])
            ->one();
        if(($latestwork['photos'] === '')){
            return false;
        }
       $latestworks = explode(',' , $latestwork['photos']);
        $path = \Yii::getAlias("@web") . '/images/latest-work-users/' . $user_id . '/';
        for($i = 0 ; $i < count($latestworks) ; $i++){
           $latestworks[$i] =  $path . $latestworks[$i];
        }

        return $latestworks;
    }
    public function getUser()
    {
        return $this->hasOne(\dektrium\user\models\User::className(), ['id' => 'user_id']);
    }

}