<?php


namespace app\models;


use yii\db\ActiveRecord;

class Message extends ActiveRecord
{
    public static function tableName()
    {
        return 'message'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
             [['text','receiver_id','sender_id','title'] , 'required'],
            [['text','title'],'string']
        ];
    }

}